# Generated by Django 4.2.4 on 2023-09-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llmApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdfdocument",
            name="document",
            field=models.TextField(blank=True, null=True),
        ),
    ]
