# Generated by Django 4.2.4 on 2023-09-03 23:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("llmApp", "0002_pdfdocument_document"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pdfdocument",
            old_name="document",
            new_name="documentContent",
        ),
    ]
